version: "3.10.12"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: application:django
    container_name: app_container
    command: python manage.py runserver 0.0.0.0:8000